### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by cvocvo** [ElmahCoreEx/ElmahCoreEx#4]
I posted here: https://github.com/ElmahCore/ElmahCore/issues/158#issuecomment-1607701229

But I think there is still a memory leak with ElmahCoreEx

We see memory usage spike and then we hit the limit on our Application Pool after 10-12 minutes just by sitting on the /elmah page. If you route to `/elmah/api/new-errors?{id}` and have it load everything, the memory leak may appear more quickly.

As a stop-gap, we have a URL rewrite that just returns a 200 response for that route; so far so good with the fixes in this repo. (This repo seems to fix the CPU usage + that URL rewrite is (at least for us) fixing the memory usage.) The URL rewrite fix doesn't prohibit loading more errors (you can still scroll down and get more) but does avoid a frontend error notification versus just doing an 'abort request' in the rewrite. I think the one caveat to this fix is that it may prevent XHR requests from loading new requests, but stability is the most crucial thing for us. We can manually refresh if needed.

Do you think there's anything that can be done about this?

**Comment by jafin** [comment]
@cvocvo what storage provider is in use ? XML/SQL ?
Is there a specific log entry that you think triggers it, if so can you attach it?
I ran a test again that endpoint and couldn't see anything that stood out, gen 0 memory is going up but GC should collect that.

![image](https://github.com/ElmahCoreEx/ElmahCoreEx/assets/127927/6dd62e1c-4a5d-4aec-820b-f07771b01ade)

Sadly for front end changes unsure, as the repo doesn't have the source code to the front end?  OG author _may_ have it, but it wasn't in the upstream repo.

**Comment by jafin** [comment]
@cvocvo  
I've tried to make some improvements and pushed a build https://www.nuget.org/packages/ElmahCoreEx/2.1.3-beta.1
If you have a change try it and let us know if it makes a difference.  Seems to be a lot of memory usage on JSON Serializer, but then the GC collects it again so seems alright.

![image](https://github.com/ElmahCoreEx/ElmahCoreEx/assets/127927/5469192a-3db7-4160-8f0d-ed3972e8b870)

**Comment by cvocvo** [comment]
We're using a SQL DB to store the error logs; I'm not sure if there's a specific log that triggers it / I'm not sure how to test that. I think that the JSON serializer changes look like an improvement, but we'll try to give that a test today or tomorrow after we deploy some other things. Thank you for publishing that as a nugget package -- that makes it faster/easier to test/rollback/manage than deploying and then manually swapping DLLs.

Edit: Getting an error trying to install from Nuget CLI:
![image](https://github.com/ElmahCoreEx/ElmahCoreEx/assets/355711/5dce4bd2-67aa-4824-9dc8-1b7611dae883)

In the dropdown, I'm only seeing the alpha 1.2 version as an option in the Nuget GUI.

Edit2: Enabled pre-release in the Nuget GUI and then installed the dependencies first -- that installs fine.

**How can I look at the memory usage like you've shown in the screenshots above?**

Edit3: Running locally I can see that the memory usage bumps up slightly when I load the page and then if I refresh the page after sitting on it for a bit, I can see the usage recover when the garbage collector runs:
![image](https://github.com/ElmahCoreEx/ElmahCoreEx/assets/355711/95ef951f-4930-4395-8632-768988fdea7d)
Not as scientific / probably useful as your graphs but I think it's a positive result. I will deploy to staging and try to analyze there, but I won't have Visual Studio to profile there.

Edit4: It seems to me that there is no longer a memory leak / no major continual increase in RAM usage just sitting on the /elmah page now. Navigating to `/elmah/api/new-errors?{id}` no longer produces any output.
I think this works! :)

**Comment by jafin** [comment]
>How can I look at the memory usage like you've shown in the screenshots above?

Jetbrains DotMemory 

I'll close this as fixed,  and release a non-beta nuget with the changes.

**Comment by cvocvo** [comment]
Thank you!

**Comment by jafin** [comment]
Published in v2.1.3 Closing..
